version: "3.8"

services:
  backend:
    build: ./backend
    env_file: ./secrets/.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    build: ./database
    env_file: ./secrets/.env.dev
    ports:
      - "5432:5432"

  redis:
    build: ./redis
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
