name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: bash deployment/ssh_setup.sh

      - name: Deploy to Server
        run: bash deployment/deploy.sh
